import "./style.scss";
import headerBg from "./assets/images/headerBg.jpg";
import logo from "./assets/images/logo.png";
import Icon from "./assets/images/Icon.png";
import gallery1 from "./assets/images/gallery1.jpg";
import gallery2 from "./assets/images/gallery2.jpg";
import gallery3 from "./assets/images/gallery3.jpg";
import gallery4 from "./assets/images/gallery4.jpg";
import galleryIcon from "./assets/images/galleryIcon.png";
import procedure1 from "./assets/images/procedure1.jpg";
import procedure2 from "./assets/images/procedure2.jpg";
import procedure3 from "./assets/images/procedure3.jpg";
import quote from "./assets/images/quote.png";
import quoteAuthor from "./assets/images/quoteAuthor.png";
import team1 from "./assets/images/team1.jpg";
import team2 from "./assets/images/team2.jpg";
import team3 from "./assets/images/team3.jpg";
import formImage from "./assets/images/formImage.jpg";
import blog1 from "./assets/images/blog1.jpg";
import blog2 from "./assets/images/blog2.jpg";
import blog3 from "./assets/images/blog3.jpg";

const images = document.getElementsByTagName("img");
images[0].src = headerBg;
images[1].src = logo;
images[2].src = Icon;
images[3].src = gallery1;
images[4].src = galleryIcon;
images[5].src = gallery2;
images[6].src = galleryIcon;
images[7].src = gallery3;
images[8].src = galleryIcon;
images[9].src = gallery4;
images[10].src = galleryIcon;
images[11].src = procedure1;
images[12].src = procedure2;
images[13].src = procedure3;
images[14].src = quote;
images[15].src = quoteAuthor;
images[16].src = team1;
images[17].src = team2;
images[18].src = team3;
images[19].src = formImage;
images[20].src = blog1;
images[21].src = blog2;
images[22].src = blog3;
images[23].src = logo;
